---

#########################################################
## Kafka-UI configure action                           ##
#########################################################

# Get port of kafka from role_container_ports
- name: Retrieve container port...
  ansible.builtin.set_fact:
    kafka_ui_port: "{{ kafka_ui_vars.container.ports[0].split(':')[0] }}"
  when: kafka_ui_vars.container.platform == "podman"

# Get IP address of Kafka UI
- name: Register variable (kafka_ui_address)...
  ansible.builtin.set_fact:
    kafka_ui_address: "http://{{ ansible_default_ipv4.address }}:{{ kafka_ui_port }}"

# Register variable for Kafka server
- name: Register variable (kafka_ui)...
  ansible.builtin.set_fact:
    kafka_ui_vars: "{{ kafka_ui_vars | combine({'address': kafka_ui_address}, recursive=true) }}"

# Configure Vault if Vault is present
- name: Configure Vault for Kafka UI
  ansible.builtin.include_tasks: configure_vault.yml
  when:
    - vault_address is defined
    - vault_token is defined
