---
#########################################################
## Vault module for Kafka UI                           ##
#########################################################
# secret engine name: kafka-ui
# secret engine type: kv
# secret name: unique id to identify vault. default '{{ ansible_fqdn | replace('.', '-') }}'

# Validate variables
- name: Validate required variables for action.
  ansible.builtin.assert:
    that: item is defined
    fail_msg: Required variable '{{ item }}' has not been provided.
    quiet: true
  with_items:
    - vault_address
    - vault_token

# Register variable (_secret_engine_name)
- name: Register variable (secret_engine_name)...
  ansible.builtin.set_fact:
    _secret_engine_name: "{{ kafka_ui_vars.secrets.secret_engine_name | default('kafka-ui') }}"

# Register variable (_secret_name)
- name: Register variable (secret_name)...
  ansible.builtin.set_fact:
    _secret_name: "{{ kafka_ui_vars.secrets.secret_name | default(ansible_fqdn | replace('.', '-')) }}"

#########################################################
## Secret Engine                                       ##
#########################################################

# Create secret_engine if it does not exist
- name: Create Vault secret engine for {{ _secret_engine_name }}...
  ansible.builtin.include_role:
    name: openbao
  vars:
    action: create_secret_engine
    secret_engine_name: "{{ _secret_engine_name }}"
    secret_engine_description: "{{ kafka_ui_vars.secrets.secret_engine_description | default('Secrets for Kafka UI.') }}"
    secret_engine_type: kv

#########################################################
## Secrets                                             ##
#########################################################

# Declare variable _secret_keyvalue
# nexus_repository_username: '{{ nexus_repository_username | default('change_me') }}'
- name: Register variable (secret_keyvalue)...
  ansible.builtin.set_fact:
    _secret_keyvalue: |
      kafka_ui_repository_url : {{ kafka_ui_vars.container.repository_url | default('change_me') }}
      kafka_ui_address : {{ kafka_ui_address | default('change_me') }}
      kafka_ui_username : {{ kafka_ui_vars.secrets.username | default('change_me') }}
      kafka_ui_password : {{ kafka_ui_vars.secrets.password | default('change_me') }}

# Store usernames and passwords in OpenBao Vault.
- name: Store Kafka server secrets and configuration data in Vault...
  ansible.builtin.include_role:
    name: openbao
  vars:
    action: create_secret
    secret_engine_name: "{{ _secret_engine_name }}"
    secret_name: "{{ _secret_name }}"
    secret_keyvalue: "{{ _secret_keyvalue | from_yaml }}"
